export const apiKeyMetrics = [
  {
    label: "Total Keys",
    value: "18",
    delta: "12.5%",
    deltaContext: "vs last 24h",
    icon: "key",
    tone: "text-blue-400",
    boxClassName: "border-blue-400/25 bg-blue-500/10",
    spark: "M0 36 L12 35 L24 33 L36 34 L48 26 L60 29 L72 20 L84 23 L96 14",
    negative: false,
  },
  {
    label: "Active Keys",
    value: "14",
    delta: "16.7%",
    deltaContext: "vs last 24h",
    icon: "shield",
    tone: "text-cyan-400",
    boxClassName: "border-cyan-400/25 bg-cyan-500/10",
    spark: "M0 37 L12 36 L24 34 L36 35 L48 29 L60 31 L72 23 L84 27 L96 17",
    negative: false,
  },
  {
    label: "Requests Today",
    value: "284K",
    delta: "8.4%",
    deltaContext: "vs yesterday",
    icon: "analytics",
    tone: "text-violet-400",
    boxClassName: "border-violet-400/25 bg-violet-500/10",
    spark: "M0 34 L12 33 L24 30 L36 32 L48 25 L60 28 L72 20 L84 24 L96 13",
    negative: false,
  },
  {
    label: "Failed Auth",
    value: "42",
    delta: "15.2%",
    deltaContext: "vs yesterday",
    icon: "bell",
    tone: "text-rose-400",
    boxClassName: "border-rose-400/25 bg-rose-500/10",
    spark: "M0 38 L12 37 L24 35 L36 36 L48 30 L60 32 L72 24 L84 27 L96 18",
    negative: true,
  },
] as const;

export const apiKeys = [
  {
    name: "Production Web SDK",
    project: "Production App",
    key: "ep_live_••••••a91f",
    permissions: "Ingest Events",
    status: "Active",
    lastUsed: "2 min ago",
    created: "Jun 18, 2026",
    requestsToday: "128K",
  },
  {
    name: "Server Events Key",
    project: "Payments Service",
    key: "ep_srv_••••••7b2c",
    permissions: "Server Write",
    status: "Active",
    lastUsed: "8 min ago",
    created: "Jun 12, 2026",
    requestsToday: "84K",
  },
  {
    name: "Marketing Tracking",
    project: "Marketing Website",
    key: "ep_mkt_••••••e44d",
    permissions: "Ingest Events",
    status: "Active",
    lastUsed: "22 min ago",
    created: "Jun 09, 2026",
    requestsToday: "51K",
  },
  {
    name: "Staging SDK Key",
    project: "Staging App",
    key: "ep_test_••••••19ac",
    permissions: "Test Events",
    status: "Inactive",
    lastUsed: "3 days ago",
    created: "May 28, 2026",
    requestsToday: "0",
  },
  {
    name: "Legacy Integration",
    project: "Production App",
    key: "ep_old_••••••902a",
    permissions: "Read/Write",
    status: "Revoked",
    lastUsed: "12 days ago",
    created: "Apr 14, 2026",
    requestsToday: "0",
  },
] as const;

export const selectedApiKeyDetails = [
  ["Name", "Production Web SDK"],
  ["Project", "Production App"],
  ["Environment", "Live"],
  ["Permissions", "Ingest Events"],
  ["Allowed Origin", "app.eventpulse.dev"],
  ["Rate Limit", "10,000 req/min"],
  ["Last Used", "2 min ago"],
] as const;

export const bestPractices = [
  "Rotate production keys every 90 days",
  "Use separate keys for client and server events",
  "Revoke unused keys immediately",
  "Never expose server keys in frontend code",
] as const;
