export const projectSummary = [
  {
    label: "Total Projects",
    value: "12",
    detail: "All time",
    icon: "cube",
    tone: "text-cyan-400",
    boxClassName: "border-blue-400/25 bg-blue-500/10",
  },
  {
    label: "Active Projects",
    value: "9",
    detail: "75% of total",
    icon: "pulse",
    tone: "text-emerald-400",
    boxClassName: "border-emerald-400/20 bg-emerald-500/10",
  },
  {
    label: "Events Today",
    value: "125,842",
    detail: "12.8% vs yesterday",
    icon: "activity",
    tone: "text-blue-400",
    boxClassName: "border-blue-400/20 bg-blue-500/10",
  },
  {
    label: "API Keys",
    value: "18",
    detail: "Across all projects",
    icon: "key",
    tone: "text-violet-400",
    boxClassName: "border-violet-400/25 bg-violet-500/10",
  },
] as const;

export const projects = [
  {
    name: "Production App",
    domain: "app.eventpulse.dev",
    status: "Active",
    events: "58,420",
    lastEvent: "2 min ago",
    apiKeys: 3,
    iconTone: "text-cyan-400",
    iconClassName: "border-cyan-400/35 bg-cyan-500/10",
  },
  {
    name: "Marketing Website",
    domain: "eventpulse.io",
    status: "Active",
    events: "34,912",
    lastEvent: "6 min ago",
    apiKeys: 2,
    iconTone: "text-violet-400",
    iconClassName: "border-violet-400/35 bg-violet-500/10",
  },
  {
    name: "Payments Service",
    domain: "payments.internal",
    status: "Active",
    events: "21,780",
    lastEvent: "12 min ago",
    apiKeys: 4,
    iconTone: "text-blue-400",
    iconClassName: "border-blue-400/35 bg-blue-500/10",
  },
  {
    name: "Staging App",
    domain: "staging.eventpulse.dev",
    status: "Inactive",
    events: "10,730",
    lastEvent: "2 days ago",
    apiKeys: 1,
    iconTone: "text-slate-300",
    iconClassName: "border-slate-500/35 bg-slate-700/20",
  },
] as const;
